name: Create Pull Request
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.TOKEN }}
          pr_label: "test pr"
          pr_title: "test pr"
