name: Tests Unitaires

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configuration de l'environnement Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installation des dépendances
        run: |
          pip install pytest

      - name: Exécution des tests
        run: pytest

  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.TOKEN }}
          pr_label: "test pr"
          pr_title: "test pr"
